/*
In der Klasse controller/Datenbankverwaltung.java die Methode verbindungMitDatenbank() beachten.
Dementsprechend eine JavaDB Datenbank anlegen mit den passenden Daten.

BENUTZER Tabelle erstellen
*/
CREATE TABLE BENUTZER (
    BENUTZERNAME VARCHAR(50) NOT NULL, 
    EMAIL VARCHAR(50) NOT NULL, 
    ISTADMIN BOOLEAN NOT NULL, 
    NACHNAME VARCHAR(50) NOT NULL, 
    PASSWORT VARCHAR(50) NOT NULL, 
    VORNAME VARCHAR(50) NOT NULL, 
    PRIMARY KEY (BENUTZERNAME)
);

/*
VERANSTALTUNGEN Tabelle erstellen
*/
CREATE TABLE VERANSTALTUNGEN (
    "NAME" VARCHAR(50) NOT NULL, 
    BESCHREIBUNG VARCHAR(50) NOT NULL, 
    ORT VARCHAR(50) NOT NULL, 
    DATUM DATE NOT NULL, 
    ZEIT TIME NOT NULL, 
    VERANSTALTER VARCHAR(50) NOT NULL, 
    MAXTEILNEHMERZAHL INTEGER NOT NULL, 
    PRIMARY KEY ("NAME")
);

/*
TEILNEHMENDEBENUTZER Tabelle erstellen
*/
CREATE TABLE TEILNEHMENDEBENUTZER (
    "NAME" VARCHAR(50) NOT NULL, 
    BENUTZERNAME VARCHAR(50) NOT NULL, 
    PRIMARY KEY ("NAME", BENUTZERNAME)
);

/*
BENOETIGTEARTIKEL Tabelle erstellen
*/
CREATE TABLE BENOETIGTEARTIKEL (
    "NAME" VARCHAR(50) NOT NULL, 
    BEZEICHNUNG VARCHAR(50) NOT NULL, 
    PRIMARY KEY ("NAME", BEZEICHNUNG)
);

/*
TEILNEHMENDEBENUTZER Tabelle erstellen
*/
CREATE TABLE VORHANDENEARTIKEL (
    "NAME" VARCHAR(50) NOT NULL, 
    BEZEICHNUNG VARCHAR(50) NOT NULL, 
    PRIMARY KEY ("NAME", BEZEICHNUNG)
);


/*
Beispieldaten
*/


INSERT INTO VTS.BENUTZER (BENUTZERNAME, EMAIL, ISTADMIN, NACHNAME, PASSWORT, VORNAME) 
	VALUES ('mklemann', 'Markus.Klemann@hs-osnabrueck.de', true, 'Klemann', 'pw', 'Markus');
INSERT INTO VTS.BENUTZER (BENUTZERNAME, EMAIL, ISTADMIN, NACHNAME, PASSWORT, VORNAME) 
	VALUES ('swachter', 'Simon.Waechter@hs-osnabrueck.de', true, 'Waechter', 'pw', 'Simon');

